language: node_js

node_js:
  - "6.1"
  - "6"
  - "4.4"

services:
  - mongodb
cache: yarn
env:
  - DBTRAVIS=travis
  - CXX=g++-4.8
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8

before_script:
  - yarn
  - mongo imk --eval 'db.hostInfo()'
  - npm install -g gulp

script: 
  - gulp
  - npm test