language: node_js

node_js:
  - "6.1"
  - "6"
  - "4.4"

services:
  - mongodb
cache: yarn
env:
  - DBTRAVIS=travis
  
before_script:
  - sleep 5
  - yarn
  - mongo imk --eval 'db.hostInfo()'
  - npm install -g gulp

script: 
  - gulp
  - npm test