language: node_js

node_js:
  - "6.1"
  - "6"
  - "4.4"

services:
  - mongodb
cache: yarn
env:
  - DBTRAVIS=travis

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-5
    - g++-5

before_script:
  - sleep 5
  - yarn
  - mongo imk --eval 'db.hostInfo()'
  - npm install -g gulp

script: 
  - gulp
  - npm test