export const INCREASE = 'INCREASE';
export const DECREASE = 'DECREASE';
export const ADD_PRODUCT = 'ADD_PRODUCT';
export const DELETE_PRODUCT = 'DELETE_PRODUCT';
export const INITIAL_PRODUCT = 'INITIAL_PRODUCT'


export const INITIAL_SUPPLIER = 'INITIAL_SUPPLIER'
export const ADD_SUPPLIER = 'ADD_SUPPLIER'
export const DELET_SUPPLIER = 'DELETE_SUPPLIER'
export const EDIT_SUPPLIER = 'EDIT_SUPPLIER'


export const INITIAL_CATEGORY = 'INITIAL_CATEGORY'